"""empty message

Revision ID: 0c8777a3a79d
Revises: 
Create Date: 2024-09-04 16:06:07.592818

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c8777a3a79d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('item_code', sa.String(length=10), nullable=False),
    sa.Column('unit_price', sa.Integer(), nullable=False),
    sa.Column('special_price', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('item_code')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('products')
    # ### end Alembic commands ###
