"""item_code-> code

Revision ID: 7e6657d44672
Revises: 0c8777a3a79d
Create Date: 2024-09-04 16:19:02.756962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e6657d44672'
down_revision = '0c8777a3a79d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('code', sa.String(length=10), nullable=False))
        batch_op.drop_column('item_code')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_code', sa.VARCHAR(length=10), autoincrement=False, nullable=False))
        batch_op.drop_column('code')

    # ### end Alembic commands ###
